CREATE TABLE IF NOT EXISTS urls (
    id SERIAL PRIMARY KEY,
    hash VARCHAR(255) NOT NULL,
    original_url TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_urls_unique_hash ON urls(hash);